## Lesson 1: Introduction to NumPy

### What is NumPy?

NumPy (Numerical Python) is a fundamental package for scientific computing with Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

### Why use NumPy?

1.  **Performance:** NumPy arrays are stored more efficiently than Python lists and are optimized for speed, especially for large datasets.
2.  **Functionality:** It offers a vast array of mathematical functions for operations on arrays, such as linear algebra, Fourier transforms, and random number capabilities.
3.  **Foundation:** Many other scientific computing libraries (like Pandas, SciPy, Scikit-learn) are built on top of NumPy.

### How to import NumPy

The standard convention is to import NumPy using the alias `np`:

In [2]:
import numpy as np

### NumPy Arrays (ndarrays)

The core object in NumPy is the `ndarray` (N-dimensional array). It's a grid of values, all of the same type, and is indexed by a tuple of non-negative integers.

#### Creating Arrays

You can create NumPy arrays from Python lists or tuples.

In [3]:
# Creating a 1-dimensional array
arr1 = np.array([1, 2, 3, 4, 5])
print('1D Array:', arr1)
print('Type of arr1:', type(arr1))
print('Shape of arr1:', arr1.shape) # (5,) means 5 elements, 1 dimension

# Creating a 2-dimensional array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print('\n2D Array:\n', arr2)
print('Shape of arr2:', arr2.shape) # (2, 3) means 2 rows, 3 columns

1D Array: [1 2 3 4 5]
Type of arr1: <class 'numpy.ndarray'>
Shape of arr1: (5,)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape of arr2: (2, 3)


NumPy also provides functions to create arrays with initial placeholder content.

In [ ]:
# Array of zeros
zeros_array = np.zeros((2, 3))
print('\nArray of Zeros:\n', zeros_array)

# Array of ones
ones_array = np.ones((1, 4))
print('\nArray of Ones:\n', ones_array)

# Array with a constant value
full_array = np.full((2, 2), 7)
print('\nArray with constant value 7:\n', full_array)

# Identity matrix
identity_matrix = np.eye(3)
print('\nIdentity Matrix (3x3):\n', identity_matrix)

# Array with a range of numbers
range_array = np.arange(0, 10, 2) # start, stop (exclusive), step
print('\nArray with range (0 to 10, step 2):', range_array)

# Array with linearly spaced numbers
linspace_array = np.linspace(0, 1, 5) # start, stop (inclusive), number of elements
print('\nArray with linearly spaced numbers (0 to 1, 5 elements):', linspace_array)


Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of Ones:
 [[1. 1. 1. 1.]]

Array with constant value 7:
 [[7 7]
 [7 7]]

Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array with range (0 to 10, step 2): [0 2 4 6 8]

Array with linearly spaced numbers (0 to 1, 5 elements): [0.   0.25 0.5  0.75 1.  ]


#### NumPy Data Types (`dtype`)

Every NumPy array has an associated data type (`dtype`). This describes the kind of elements in the array (e.g., integers, floats, booleans). Having a uniform data type across the array is one reason NumPy arrays are so efficient.

In [4]:
int_array = np.array([1, 2, 3])
print('Integer Array:', int_array, 'dtype:', int_array.dtype)

float_array = np.array([1.0, 2.5, 3.7])
print('Float Array:', float_array, 'dtype:', float_array.dtype)

# Explicitly define dtype
explicit_float_array = np.array([1, 2, 3], dtype=np.float64)
print('Explicit Float Array:', explicit_float_array, 'dtype:', explicit_float_array.dtype)

# Type conversion
converted_int_array = explicit_float_array.astype(np.int32)
print('Converted to Int32:', converted_int_array, 'dtype:', converted_int_array.dtype)

Integer Array: [1 2 3] dtype: int64
Float Array: [1.  2.5 3.7] dtype: float64
Explicit Float Array: [1. 2. 3.] dtype: float64
Converted to Int32: [1 2 3] dtype: int32


#### Manipulating Array Shapes

The `shape` of an array describes the dimensions of the array. You can change the shape of an array without changing its data.

In [5]:
original_array = np.arange(12)
print('Original Array:', original_array, '\nShape:', original_array.shape)

# Reshape to a 3x4 matrix
reshaped_array = original_array.reshape(3, 4)
print('\nReshaped to 3x4:\n', reshaped_array, '\nShape:', reshaped_array.shape)

# Flatten back to a 1D array
flattened_array = reshaped_array.flatten()
print('\nFlattened Array:', flattened_array, '\nShape:', flattened_array.shape)

# Transpose a matrix (swapping rows and columns)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print('\nOriginal Matrix:\n', matrix, '\nShape:', matrix.shape)
transposed_matrix = matrix.T
print('\nTransposed Matrix:\n', transposed_matrix, '\nShape:', transposed_matrix.shape)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11] 
Shape: (12,)

Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
Shape: (3, 4)

Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11] 
Shape: (12,)

Original Matrix:
 [[1 2 3]
 [4 5 6]] 
Shape: (2, 3)

Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]] 
Shape: (3, 2)


#### More Common NumPy Functions

NumPy provides many functions for aggregation, statistical analysis, and more. Here are a few examples:

In [ ]:
data = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print('Sum of all elements:', np.sum(data))

# Sum along axis 0 (columns)
print('Sum along columns:', np.sum(data, axis=0))

# Mean of all elements
print('Mean of all elements:', np.mean(data))

# Max value
print('Maximum value:', np.max(data))

# Index of max value (flattened array)
print('Index of maximum value:', np.argmax(data))

# Standard deviation
print('Standard deviation:', np.std(data))

Sum of all elements: 21
Sum along columns: [5 7 9]
Mean of all elements: 3.5
Maximum value: 6
Index of maximum value: 5
Standard deviation: 1.707825127659933


#### Basic Array Operations

In [ ]:
arr_a = np.array([10, 20, 30, 40])
arr_b = np.array([1, 2, 3, 4])

# Element-wise addition
print('Addition:', arr_a + arr_b)

# Element-wise subtraction
print('Subtraction:', arr_a - arr_b)

# Element-wise multiplication
print('Multiplication:', arr_a * arr_b)

# Element-wise division
print('Division:', arr_a / arr_b)

# Squaring elements
print('Squaring:', arr_a**2)

# Universal functions (ufuncs)
print('Square root:', np.sqrt(arr_a))
print('Sine:', np.sin(arr_a))

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Squaring: [ 100  400  900 1600]
Square root: [3.16227766 4.47213595 5.47722558 6.32455532]
Sine: [-0.54402111  0.91294525 -0.98803162  0.74511316]


#### Indexing and Slicing

NumPy arrays can be indexed and sliced similar to Python lists.

In [ ]:
my_array = np.array([10, 20, 30, 40, 50, 60])

# Accessing a single element
print('First element:', my_array[0])
print('Third element:', my_array[2])

# Slicing: elements from index 1 to 4 (exclusive)
print('Slice (1 to 4):', my_array[1:4])

# Slicing from the beginning to index 3 (exclusive)
print('Slice (start to 3):', my_array[:3])

# Slicing from index 2 to the end
print('Slice (2 to end):', my_array[2:])

# Using a step in slicing
print('Slice with step 2:', my_array[::2])

# 2D array indexing
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print('\nOriginal Matrix:\n', matrix)

# Access element at row 1, column 2 (0-indexed)
print('Element at (1, 2):', matrix[1, 2]) # which is 6

# Get the first row
print('First row:', matrix[0, :])

# Get the second column
print('Second column:', matrix[:, 1])

# Get a sub-matrix (rows 0-1, cols 1-2)
print('Sub-matrix:\n', matrix[0:2, 1:3])

First element: 10
Third element: 30
Slice (1 to 4): [20 30 40]
Slice (start to 3): [10 20 30]
Slice (2 to end): [30 40 50 60]
Slice with step 2: [10 30 50]

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 2): 6
First row: [1 2 3]
Second column: [2 5 8]
Sub-matrix:
 [[2 3]
 [5 6]]


## Mathematical Operations and Vectorization

### Mathematical Operations
NumPy allows you to perform mathematical operations on entire arrays without needing to loop through individual elements. This is often referred to as element-wise operations. These operations are significantly faster than traditional Python loops, especially for large arrays.

In [ ]:
import numpy as np

# Let's redefine arr_a and arr_b for this example for clarity, or use existing ones if available
# Assuming arr_a and arr_b were defined earlier as:
arr_a = np.array([10, 20, 30, 40])
arr_b = np.array([1, 2, 3, 4])

print('Array A:', arr_a)
print('Array B:', arr_b)

# Element-wise addition
print('\nElement-wise Addition (arr_a + arr_b):', arr_a + arr_b)

# Element-wise subtraction
print('Element-wise Subtraction (arr_a - arr_b):', arr_a - arr_b)

# Element-wise multiplication
print('Element-wise Multiplication (arr_a * arr_b):', arr_a * arr_b)

# Element-wise division
print('Element-wise Division (arr_a / arr_b):', arr_a / arr_b)

# Element-wise exponentiation
print('Element-wise Exponentiation (arr_a ** 2):', arr_a ** 2)

# Universal functions (ufuncs) apply element-wise
print('Square root of arr_a (np.sqrt(arr_a)):', np.sqrt(arr_a))
print('Sine of arr_b (np.sin(arr_b)):', np.sin(arr_b))

### Vectorization
Vectorization is the process of performing operations on entire arrays or matrices rather than on individual elements. This approach is highly optimized in NumPy because many of its operations are implemented in C, leading to substantial performance improvements. It's a key reason why NumPy is so powerful for scientific computing.

In [7]:
import time

# Demonstrate Vectorization vs. Python Loops

# Create a large NumPy array
large_array = np.arange(1, 1000001)

print('--- Vectorized Operation (NumPy) ---')
start_time = time.time()
vectorized_result = large_array * 2
end_time = time.time()
print(f'Time taken for vectorized operation: {end_time - start_time:.6f} seconds')
# print('First 5 elements of vectorized result:', vectorized_result[:5]) # Uncomment to see output

print('\n--- Traditional Python Loop ---')
python_list = list(range(1, 1000001))
start_time = time.time()
looped_result = []
for x in python_list:
    looped_result.append(x * 2)
end_time = time.time()
print(f'Time taken for Python loop: {end_time - start_time:.6f} seconds')
# print('First 5 elements of looped result:', looped_result[:5]) # Uncomment to see output

print('\nAs you can see, the vectorized NumPy operation is significantly faster for large datasets.')

--- Vectorized Operation (NumPy) ---
Time taken for vectorized operation: 0.006001 seconds

--- Traditional Python Loop ---
Time taken for Python loop: 0.141244 seconds

As you can see, the vectorized NumPy operation is significantly faster for large datasets.
